### PR TITLE
Escape spaces in path

### LINKED ISSUE #46: Secure variable files with spaces in the name produce error
When using a secure variable file whose name contains a space, the constructed terraform command is invalid. If the secure file name is `my secure var file.tfvars` then apply task constructs the command as
```
terraform apply -var-file=/home/vsts/work/_temp/my secure var file.tfvars -auto-approve /home/vsts/work/r1/a/terraform.tfplan
```

which then produces the following error
```
2019-03-13T16:08:24.9284515Z ‌Usage: terraform apply [options] [DIR-OR-PLAN]‌
2019-03-13T16:08:24.9285854Z 
2019-03-13T16:08:24.9286366Z   Builds or changes infrastructure according to Terraform configuration
2019-03-13T16:08:24.9286881Z   files in DIR.
2019-03-13T16:08:24.9287265Z 
2019-03-13T16:08:24.9287815Z   By default, apply scans the current directory for the configuration
2019-03-13T16:08:24.9288267Z   and applies the changes appropriately. However, a path to another
2019-03-13T16:08:24.9288682Z   configuration or an execution plan can be provided. Execution plans can be
2019-03-13T16:08:24.9289418Z   used to only execute a pre-determined set of actions.
2019-03-13T16:08:24.9296998Z 
2019-03-13T16:08:24.9297436Z Options:
2019-03-13T16:08:24.9298346Z 
2019-03-13T16:08:24.9298953Z   -backup=path           Path to backup the existing state file before
2019-03-13T16:08:24.9299637Z                          modifying. Defaults to the "-state-out" path with
2019-03-13T16:08:24.9300267Z                          ".backup" extension. Set to "-" to disable backup.
2019-03-13T16:08:24.9300746Z 
2019-03-13T16:08:24.9301887Z   -auto-approve          Skip interactive approval of plan before applying.
2019-03-13T16:08:24.9302251Z 
2019-03-13T16:08:24.9302872Z   -lock=true             Lock the state file when locking is supported.
2019-03-13T16:08:24.9303210Z 
2019-03-13T16:08:24.9303813Z   -lock-timeout=0s       Duration to retry a state lock.
2019-03-13T16:08:24.9304153Z 
2019-03-13T16:08:24.9304888Z   -input=true            Ask for input for variables if not directly set.
2019-03-13T16:08:24.9305243Z 
2019-03-13T16:08:24.9305729Z   -no-color              If specified, output won't contain any color.
2019-03-13T16:08:24.9306084Z 
2019-03-13T16:08:24.9306593Z   -parallelism=n         Limit the number of parallel resource operations.
2019-03-13T16:08:24.9306985Z                          Defaults to 10.
2019-03-13T16:08:24.9307267Z 
2019-03-13T16:08:24.9307774Z   -refresh=true          Update state prior to checking for differences. This
2019-03-13T16:08:24.9308181Z                          has no effect if a plan file is given to apply.
2019-03-13T16:08:24.9308786Z 
2019-03-13T16:08:24.9309534Z   -state=path            Path to read and save state (unless state-out
2019-03-13T16:08:24.9309966Z                          is specified). Defaults to "terraform.tfstate".
2019-03-13T16:08:24.9310243Z 
2019-03-13T16:08:24.9311301Z   -state-out=path        Path to write state to that is different than
2019-03-13T16:08:24.9311996Z                          "-state". This can be used to preserve the old
2019-03-13T16:08:24.9312452Z                          state.
2019-03-13T16:08:24.9312776Z 
2019-03-13T16:08:24.9313344Z   -target=resource       Resource to target. Operation will be limited to this
2019-03-13T16:08:24.9313856Z                          resource and its dependencies. This flag can be used
2019-03-13T16:08:24.9314762Z                          multiple times.
2019-03-13T16:08:24.9315027Z 
2019-03-13T16:08:24.9316056Z   -var 'foo=bar'         Set a variable in the Terraform configuration. This
2019-03-13T16:08:24.9316415Z                          flag can be set multiple times.
2019-03-13T16:08:24.9316722Z 
2019-03-13T16:08:24.9317272Z   -var-file=foo          Set variables in the Terraform configuration from
2019-03-13T16:08:24.9318240Z                          a file. If "terraform.tfvars" or any ".auto.tfvars"
2019-03-13T16:08:24.9318922Z                          files are present, they will be automatically loaded.‌
2019-03-13T16:08:24.9319939Z ##[debug]Exit code 1 received from tool '/opt/hostedtoolcache/terraform/0.11.10/x64/terraform'
2019-03-13T16:08:24.9320516Z ##[debug]STDIO streams have closed for tool '/opt/hostedtoolcache/terraform/0.11.10/x64/terraform'
2019-03-13T16:08:24.9367904Z ##[debug]task result: Failed
2019-03-13T16:08:24.9431903Z ##[error]Error: The process '/opt/hostedtoolcache/terraform/0.11.10/x64/terraform' failed with exit code 1
```

### PR DESCRIPTION
**Pull request by favoretti**
Fixes #46

### CODE REVIEW

File: TerraformCLI/src/terraform-runner.ts [hunk 1]
```diff
@@ -98,6 +98,7 @@ export class TerraformWithSecureVarFile extends TerraformCommandDecorator{
                 if(context.command.name === 'init') {
                     throw "terraform init command supports only env files, no tfvars are allowed during this stage.";
                 }
+                secureFilePath = secureFilePath.replace(/ /g, '\\ ');
```
Comment (charleszipp) [inline TerraformCLI/src/terraform-runner.ts:101]: Can we update one of the existing unit tests to use a space in the secure var file name? I think this would only require changing a couple lines in one of the `*-azurerm-with-secure-var-file.env.ts` files under plan, apply, destroy, or refresh. Update the actual file name to have a space and the expected command to reflect the espace pattern we expect to see when there is a space. 

This example is from one of the tests I added for import support.
```javascript
// update to use a file with a space in the name (i.e. default foo.vars)
const secureVarsFileName: string = "./.bin/tests/terraform-import/default.vars";
const resourceAddress = "azurerm_resource_group.rg"
const resourceId = "/subscriptions/sub1/resourceGroups/rg-tffoo-dev-eastus"

// update to have the expected escape pattern
const expectedArgs = `-var-file=${secureVarsFileName} ${resourceAddress} ${resourceId}`
```

Comment (charleszipp) [inline TerraformCLI/src/terraform-runner.ts:101]: Can we update one of the existing unit tests to use a space in the secure var file name? I think this would only require changing a couple lines in one of the `*-azurerm-with-secure-var-file.env.ts` files under plan, apply, destroy, or refresh. Update the actual file name to have a space and the expected command to reflect the espace pattern we expect to see when there is a space. 

This example is from one of the tests I added for import support.
```javascript
// update to use a file with a space in the name (i.e. default foo.vars)
const secureVarsFileName: string = "./.bin/tests/terraform-import/default.vars";
const resourceAddress = "azurerm_resource_group.rg"
const resourceId = "/subscriptions/sub1/resourceGroups/rg-tffoo-dev-eastus"

// update to have the expected escape pattern
const expectedArgs = `-var-file=${secureVarsFileName} ${resourceAddress} ${resourceId}`
```

Comment (favoretti) [reply TerraformCLI/src/terraform-runner.ts:101]: @charleszipp Modified one of the tests.

File: TerraformCLI/src/terraform-runner.ts [hunk 2]
```diff
@@ -87,7 +87,7 @@ export class TerraformWithSecureVarFile extends TerraformCommandDecorator{
     }
     async onRun(context: TerraformCommandContext): Promise<void> {        
         if(this.secureVarFileId){
-            const secureFilePath = await this.taskAgent.downloadSecureFile(this.secureVarFileId);
+            var secureFilePath = await this.taskAgent.downloadSecureFile(this.secureVarFileId);
```
Comment (charleszipp) [inline TerraformCLI/src/terraform-runner.ts:90]: FYI only, for variables that are intended to be mutable such as this one, use `let`. Typically now either `let` or `const` keywords are used instead of `var` depending on if you expect the value to change or be readonly.

File: TerraformCLI/src/tests/terraform-plan/plan-azurerm-with-secure-var-file.env.ts [hunk 3]
```diff
@@ -13,8 +13,8 @@ const expectedEnv: { [key: string]: string } = {
 
 const terraformCommand: string = 'plan';
 const secureVarsFileId: string = "6b4ef608-ca4c-4185-92fb-0554b8a2ec72"
-const secureVarsFileName: string = "./.bin/tests/terraform-plan/default.vars";
-const commandArgs: string = `-var-file=${secureVarsFileName}`;
+const secureVarsFileName: string = "./.bin/tests/terraform-plan/default file with spaces.vars";
```
Comment (charleszipp) [inline TerraformCLI/src/tests/terraform-plan/plan-azurerm-with-secure-var-file.env.ts:16]: Thanks for adding this! that will help people understand what should happen if a file with spaces is used.
